from specc import *


writest('Initializing A-Team..')
pd1 = leclass()
han = leclass('Hannibal')
fac = leclass('Face')
ba = leclass('B.A.')
mur = leclass('Murdock')
writest('..done')

writest('Feeding database..\nfor Hannibal..')
han.setAttr('first_name', 'John')
han.setAttr('last_name', 'Smith')
han.setAttr('rank', 'Lieutenant Colonel')
han.setAttr('alias', 'Hannibal')
writest('for Face..')
fac.setAttr('first_name', 'Templeton')
fac.setAttr('last_name', 'Peck')
fac.setAttr('rank', 'First Lieutenant')
fac.setAttr('alias', 'Face / Faceman')
writest('for B.A. ..')
ba.setAttr('first_name', 'Bosco Albert')
ba.setAttr('last_name', 'Baracus')
ba.setAttr('rank', 'Master Sergeant')
ba.setAttr('alias', 'B.A. / Bad Attitude')
writest('for Murdock..')
mur.setAttr('first_name', 'H. M.')
mur.setAttr('last_name', 'Murdock')
mur.setAttr('rank', 'Captain')
mur.setAttr('alias', 'Murdock / Howling Mad')
writest('..done')

writest('Listing..')
writest(' ')
han.getAll()
writest(' ')
fac.getAll()
writest(' ')
ba.getAll()
writest(' ')
mur.getAll()
writest(' ')
han.getInfo()