#!/bin/bash

## usage:     gseq810 [text] [sleep time in seconds]
#example1:  gseq810 hello
#example2:  gseq810 hello 0.5
#example3:  gseq810 "hello world"
#example4:  gseq810 "Hello world" 2

## dependencies: https://github.com/MatMoul/g810-led
#   modified udevd:       /etc/udev/rules.d or s.th. similar      -> remove the part in which it loads the default profile
#   default profile:      /etc/g810-led/profile                   -> end file with c in last line (commit).


text=$1
slp=$2
[[ -z "$slp" ]] && slp=0.5

#g810-led -dv 046d -a 000000 && sleep 0.1
#g810-led -dv 046d -a ffffff && sleep 0.1
#g810-led -dv 046d -a 000000 && sleep 0.1

for ((i=1;i<=${#text};i++))
do
k=${text:$i-1:1}
[[ "${text:$i-1:1}" == " " ]] && k=space
g810-led -dv 046d -k $k ff0000
sleep $slp
g810-led -dv 046d -p /etc/g810-led/profile
sleep 0.1
done

: <<'END' 

-a: all
-g: group
-k: key
-p: profile


Group List :
    logo
    indicators
    fkeys
    modifiers
    multimedia
    arrows
    numeric
    functions
    keys


Group Logo :
    logo

Group indicators :
    num_indicator, numindicator, num
    caps_indicator, capsindicator, caps
    scroll_indicator, scrollindicator, scroll
    game_mode, gamemode, game
    back_light, backlight, light

Group fkeys :
    f1 - f12

Group modifiers :
    shift_left, shiftleft, shiftl
    ctrl_left, ctrlleft, ctrll
    win_left, winleft, win_left
    alt_left, altleft, altl
    alt_right, altright, altr, altgr
    win_right, winright, winr
    menu
    ctrl_right, ctrlright, ctrlr
    shift_right, shiftright, shiftr

Group multimedia :
    mute
    play_pause, playpause, play
    stop
    previous, prev
    next

Group arrows :
    arrow_top, arrowtop, top
    arrow_left, arrowleft, left
    arrow_bottom, arrowbottom, bottom
    arrow_right, arrowright, right

Group numeric :
    num_lock, numlock
    num_slash, numslash, num/
    num_asterisk, numasterisk, num*
    num_minus, numminus, num-
    num_plus, numplus, num+
    numenter
    num0 - num9
    num_dot, numdot, num.

Group functions :
    escape, esc
    print_screen, printscreen, printscr
    scroll_lock, scrolllock
    pause_break, pausebreak
    insert, ins
    home
    page_up, pageup
    delete, del
    end
    page_down, pagedown

Group keys :
    0 - 9
    a - z
    tab
    caps_lock, capslock
    space
    backspace, back
    enter
    tilde
    minus
    equal
    open_bracket
    close_bracket
    backslash
    semicolon
    dollar
    quote
    intl_backslash
    comma
    period
    slash


END

exit 0