#!/bin/bash

[[ "$(whoami)" == "root" ]] || { echo "Please run as root!" && exit 1; }

# root is mounted here 																-> /dev/sdc1
rootpath=$(mount | grep "/ " | awk '{print $1}')	 

# delivers last character of $rootpath 												-> 1
rootpart=${rootpath:(-1)}

# delivers path to device 															-> /dev/sdc
#${rootpath: 0:-1}	

# split (delimeter is '/') and save in temporary array 'a'; then print third item 	-> sdc1
rootdevicepn=$(echo $rootpath | awk '{split($0,a,"/"); print a[3]}')

# cut last character																-> sdc
rootdevice=${rootdevicepn: 0:-1}	

# delivers all partitions of the rootdisk in an array								-> [sdc1; sdc2]
#partsindev=($(lsblk | grep $rootdevice | grep part | awk '{print $1}' | awk '{split($0,a,"─"); print a[2]}'))

# delivers all partitions of the rootdisk in an array								-> [1; 2]
partsindev=($(lsblk | grep $rootdevice | grep part | awk '{print $1}' | awk '{split($0,a,"─"); print a[2]}' | awk '$0=$NF' FS= ))
		
# already mounted partitions of the rootdisk in an array							-> [1; 2]
alrdymntd=($(mount | grep $rootdevicepn | awk '{print $1}' | awk '{split($0,a,"/"); print a[3]}' | awk '$0=$NF' FS= ))		

# those partitions which are not mounted already in an array						-> [1; 2]
tomount=($(echo ${partsindev[@]} ${alrdymntd[@]} | tr ' ' '\n' | sort | uniq -u))

# ntfsfix basically..
elsecase() {
	drivepath=$1
	echo "--Doing ntfsfix on $device--" 
	sudo ntfsfix $drivepath 
	echo "--remounting $device--" 
	sudo mount -vo remount,rw $drivepath 
	printf "\n... done with workaround!\n\n"
	#sudo cat $templog >> $logpath    #append
	#sudo cat $templog > $logpath    #replace
	echo " " 
}

# main -> get input, mount, check
runsth() {
	partpath=$1
	pdrivepath=/dev/$partpath
	pmountpath=/mnt/$partpath
#: <<'END'
	sudo mkdir -p /mnt/$partpath

	sudo mount -t auto -v $pdrivepath $pmountpath 
	errlev=${PIPESTATUS[0]}

	if [ $errlev -eq 0 ]
	then
	#	if [ -w $mountpath/pagefile.sys ] 
		if touch $pmountpath/AA
		then
			printf "... done\n\n"
		else
			echo "--errorlevel: $errlev, but no writing permissions--"
			elsecase $pdrivepath 
		fi
	else
		echo "--errorlevel: $errlev--" 
		elsecase $pdrivepath 
	fi
#END
	#echo "dry run: mounting $pdrivepath to $pmountpath"
}

#obsoleted:
#for i in ${partsindev[@]}; do [[ "$i" != "$rootpart" ]] && runsth $rootdevice$i; done	# -> sdc2, sdc3, sdc4, ... except the one with root

for i in ${tomount[@]}; do runsth $rootdevice$i; done	# -> sdc2, sdc3, sdc4, ... except the one with root

exit 0