#!/bin/bash

[[ "$(whoami)" == "root" ]] || { echo "Please run as root!" && exit 1; }

rootpath=$(mount | grep "/ " | awk '{print $1}')	# root is mounted here 	-> /dev/sdc1 

rootpart=${rootpath:(-1)} 	# delivers last character of $rootpath 			-> 1
#${rootpath: 0:-1}	# delivers path to device 								-> /dev/sdc
rootdevicepn=$(echo $rootpath | awk '{split($0,a,"/"); print a[3]}')
# split (delimeter is '/') and save in array 'a'; then print third item 	-> sdc1
rootdevice=${rootdevicepn: 0:-1}	# cut last character					-> sdc


# mount | grep dev/sdc | wc -l 		or 	mount | grep sdc | wc -l	delivers only the number of mounted partitions on the disk

#partsindev=($(lsblk | grep $rootdevice | grep part | awk '{print $1}' | awk '{split($0,a,"─"); print a[2]}'))
## ## 	delivers all partitions of the rootdisk in an array				-> [sdc1; sdc2]
partsindev=($(lsblk | grep $rootdevice | grep part | awk '{print $1}' | awk '{split($0,a,"─"); print a[2]}' | awk '$0=$NF' FS= ))
#		delivers all partitions of the rootdisk in an array				-> [1; 2]


#todo: mount all partitions except those that are already mounted

elsecase() {
	drivepath=$1
	echo "--Doing ntfsfix on $device--" 
	sudo ntfsfix $drivepath 
	echo "--remounting $device--" 
	sudo mount -vo remount,rw $drivepath 
	printf "\n... done with workaround!\n\n"
	#sudo cat $templog >> $logpath    #append
	#sudo cat $templog > $logpath    #replace
	echo " " 
}

runsth() {
	partpath=$1
	pdrivepath=/dev/$partpath
	pmountpath=/mnt/$partpath

	sudo mkdir -p /mnt/$partpath

	sudo mount -t auto -v $pdrivepath $/mnt/$pmountpath 
	errlev=${PIPESTATUS[0]}

	if [ $errlev -eq 0 ]
	then
	#	if [ -w $mountpath/pagefile.sys ] 
		if touch $pmountpath/AA
		then
			printf "... done\n\n"
		else
			echo "--errorlevel: $errlev, but no writing permissions--"
			elsecase $pdrivepath 
		fi
	else
		echo "--errorlevel: $errlev--" 
		elsecase $pdrivepath 
	fi

	#echo "dry run: mounting $pdrivepath to $pmountpath"
}


for i in ${partsindev[@]}; do [[ "$i" != "$rootpart" ]] && runsth $rootdevice$i; done	# -> sdc2, sdc3, sdc4, ... except the one with root

exit 0