#! /bin/sh

case "$1" in
    --info)
        echo " "
	echo "This script does nothing!"
        echo " "
        echo "Just wanted to try out something"
        echo " "
	;;
    *)
	echo "Usage: ...there is no use case"
        echo "Or try 'testmest --info' for more information"
        exit 1
        ;;
esac

exit 0
